"use strict";
exports.__esModule = true;
require("reflect-metadata");
var express_1 = require("express");
require("./database");
require("./shared/container");
var routes_1 = require("./routes");
require("dotenv/config");
var cors_1 = require("cors");
var Sentry = require("@sentry/node");
var handlingErrors_1 = require("./middlewares/handlingErrors");
var app = express_1["default"]();
app.use(Sentry.Handlers.requestHandler());
app.use(Sentry.Handlers.tracingHandler());
app.use(express_1["default"].json());
app.use(cors_1["default"]());
app.use(routes_1.router);
app.use(Sentry.Handlers.errorHandler());
app.use(handlingErrors_1.handlingErrors);
var port = process.env.PORT || 3333;
app.listen(port, function () { return console.log("Server is running!", port); });
